stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t my-app:latest .

test:
  stage: test
  script:
    - echo "Running tests..."  # Replace with actual test commands if available

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
